pixijs-userland/pixi-viewport

src/clamp-zoom.js, src/viewport.js
This is important so that if the window size is changed, the viewport maintains its contraints.
e.g. If the viewport is at its max constraints and the window size increases, the viewport should clamp to those max contraints rather than allow the viewport to show more of the world.
=> Updates clamp() upon resizing of the viewport

src/drag.js
The 'drag-end' event would fire upon pressing and releasing the mouse/finger from the screen without actually dragging or having fired the 'drag-start' event first. This fixes that.
_P.S. Lovin' the events system!_
=> Fixed 'drag-end' firing prematurely

src/viewport.js
Code worked during testing because the "width" parameter would act as the options.
=> Removed width and height parameters from snapZoom function

@types/index.d.ts
`on` and `listeners` overridden methods should not cause any more troubles for Typescript users.
Tested on bare bones example provided here: https://github.com/davidfig/pixi-viewport/issues/63#issuecomment-413350949
Fixes: #63
=> Fixes typescript definition issues.

src/viewport.js
As destroy method supports `options` param, we need to make sure to pass
provided options to the super call to maintain their cascading behavior.
A quote from the pixi.js documentation:
> children	boolean	false	optional
> if set to true, all the children will have their destroy method called as well.
> 'options' will be passed on to those calls.
=> Fix for destroy called with options

src/viewport.js
This allows me to scale the world only along a single axis. This is
useful in a 2D function visualization where I need to scale the view
along the Y axis.
=> viewport.fitHeight() / fitWidth(): add optional scale param

src/wheel.js
Fixes https://github.com/davidfig/pixi-viewport/issues/119
This is the logic d3-zoom uses for its scroll wheel support. I tested on a Mac trackpad and Windows 10 with a SteelSeries Sensei mouse.
Somewhat related, your demo page has the "bounce" plugin on by default, and 100% honest the first time I looked at the demo I didn't realize and thought pixi-viewport was super buggy 😢 I would personally suggest turning that off to avoid confusing people in the demo, but it's obviously your call so I'm just suggesting it.
=> Incorporates better zoom logic for mac trackpads

@types/index.d.ts
It got lost in https://github.com/davidfig/pixi-viewport/commit/3198d6ab2cade7df47b82699415258bd2f36c515
=> Add missing screenHeight property to types

@types/index.d.ts
It got removed in [#3198d6ab2cade7df47b82699415258bd2f36c515](https://github.com/davidfig/pixi-viewport/commit/3198d6ab2cade7df47b82699415258bd2f36c515)
=> Add missing getVisibleBounds method to types

src/plugins/drag.js
Adds a `keyToPress` property to the `dragOptions`. Setting a keyCode for this option will stop the drag event from being triggered if the corresponding key is not pressed.
=> Check for keypress before triggering drag event

src/plugin-manager.js, src/plugins/bounce.js, src/plugins/clamp-zoom.js, src/plugins/clamp.js
at the moment using of reset is organized directly in the plugin-manager and not using the reset of plugin selfe. so it is only workling with the plugins which are included, else i also have to overwritte the plugin-manager.
=> use reset from plugins instead manage in plugin-manager

@types/index.d.ts
I found a declaration for MovedEventData that was not used anywhere. 
This one will fix it.
=> fix(typings): add MovedEventType type declaration

src/viewport.js
The viewport is currently not marked dirty when only size is changed, so content gets stretched until next render.
=> Mark viewport dirty after resizing

@types/index.d.ts
We could include [all possible key codes](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code/code_values) as KeyCodeType. But I hope this is enough of a start for the common cases.
=> Add keyToPress and ignoreKeyToPressOnTouch to DragOptions

@types/index.d.ts
Per discussion on https://github.com/davidfig/pixi-viewport/pull/234
[Typescript playground link](https://www.typescriptlang.org/play?#code/PTAEGEEMGcFNQIwC5QBED2tqgHboC6jQAW6A7qPsfOgA74CW6O2DOob+sANtw3C1gAofAE9a8AGqwA5gyygAvKADktAK4BbWgGs2K0AB9VAY3VnNAI1gAnA8ej4bbGUO6xCAN2ShpchcrAAFRoPB7wVPA2WISQOAAmoLTR0Ngm+NwA1NC0kCbwQWAqZhbWdm4eoJ4ATCh+8tjKKgBe5ibEbAwqQkIgEDDwtaAAyqRk2JGgdIzMrOycPHwCcCLi8ABiNuoM+I2qkLS07tD2qug2cTJYpwAUjs44MqAAZKAA3gC+AJQVhABmPk2212SlAwVC7i4lGooBSsQSSRSaQy2Vy+VAhX2h2O3UhoD+QyBOz2Khk6kgnkgBj6VH4lDWoHasBMOgm6HQQA) for testing
=> In type definitions: change string to (string & {}) when in union with literals

@types/index.d.ts, src/input-manager.js, src/plugin-manager.js, src/plugins/clamp.js, src/plugins/drag.js, src/plugins/plugin.js
PIXI 5.3.0 removed the `interaction` namespace and put the enclosed stuff in the top-level `PIXI` namespace (https://github.com/pixijs/pixi.js/pull/6681).
This PR fixes the typescript types for PIXI 5.3.0 (though this will then break them for those using older versions of PIXI).
I also removed a duplicate definition of the `DragOptions` type.
=> Update Typescript Definitions for PIXI 5.3.0

@types/index.d.ts
screenWorldWidth and screenWorldHeight were missing from type definition.
Also fixed naming of screenHeightInWorldPixels.
=> Added missing @types definitions

src/plugins/drag.js
Not sure if this is the right fix but it fixed the problem for me. It appears that this.parent has no addEventListener function.
`Uncaught TypeError: this.parent.addEventListener is not a function`
So instead I'm adding the event listener to the window.
I couldn't find where these listeners get removed or I would have added that as well.
=> Fixed Uncaught TypeError when adding keyToPress to drag options

src/input-manager.js
Scrolling on a DOM element placed over the canvas will trigger the zooming feature. This fix adds a explicit check against the interactionDOMElement defined in the interaction plugin.
Fixes #255
=> Fix captured wheel event from a different dom element

@types/index.d.ts
`toWorld()` works with a rectangle (eg the result of getBounds()), but the type `PIXI.Point` doesn't have enough overlap and tsserver raises an error.
We should be able to call `viewport.toWorld(sprite.getBounds())`
When reading the code, I noticed that toWorld is calling pixi.js toLocal, which takes an IPointData as input
```tsx
export interface IPointData
{
x: number;
y: number;
}
/**
* Common interface for points. Both Point and ObservablePoint implement it
* @memberof PIXI
* @interface IPointData
*/
```
This would match a rectangle, and hide type errors.
I suppose that docstrings in viewport.js and other types like toScreen param could also be updated the same way.
=> Fix toWorld parameter's type

src/plugins/Decelerate.ts
I added a condition that detects if both axes are active and both are less than minSpeed, if this is correct then I stop them.
This is to make it stop better when minSpeed value is high
=> Visual improvement of minSpeed in Decelerate

src/Viewport.ts, src/plugins/Animate.ts
Currently we don't use those classes so interface `{x:number, y: number}` would be enough
=> Improve point type

README.md
The current thank-you-shoutout is spelled differently and the link 404s
=> Fix ShukantPal's name/link in README.md

src/plugins/MouseEdges.ts
The wrong variable was used, causing strange behavior when using MouseEdge with distance, for Right and Bottom. 
This issue was mentioned here: https://github.com/davidfig/pixi-viewport/issues/263
@davidfig
=> Mouse edge distance fix

src/PluginManager.ts, src/plugins/Drag.ts
Hi! I tried to implement fix for event listeners leak, like was mentioned [here](https://github.com/davidfig/pixi-viewport/issues/402#issuecomment-1273796162)
I implemented the easiest approach, because I think that handling keyboard events inside plugins is not the best practice, because if you use Drag and Wheel plugin at the same time, you should handle keyboard events yourself :(
I wanted to use Ctrl+scroll for zoom and just just scroll for scrolling the viewport, and I cant figure out how to do that without handling keyboard events myself.
=> fix event listener leak in drag plugin

README.md
In 5.2 viewport's version a breaking change was made, that replaced `interactive` boolean with `eventMode`, which means that people with pixi.js < 7.2 are not able to use v5.2
Seems that those changes should be emphasized in readme.
=> Update README.md for v5.2 (interactive deprecation)

src/InputManager.ts, src/Viewport.ts
Fixes #438
This pull request adds an optional chaining operator to the `events.domElement` property when calling `removeEventListener`. This means that this will no longer error out when the Pixi prematurely destroys the domElement ahead of pixi-viewport.
Also removes the need to do this in userland for @pixi/react:
```
willUnmount: (viewport: PixiViewport) => {
viewport.options.noTicker = true;
viewport.destroy({ children: true });
}
```
I've tested this locally using `pnpm patch` on my application and it works wonders.
=> Fix removeEventListener error (PixiJS 7)

src/plugins/Drag.ts, src/plugins/Pinch.ts, src/plugins/Wheel.ts
Addresses https://github.com/davidfig/pixi-viewport/issues/49
Currently this library assumes that the Viewport exists in global coordinate space, i.e, on the root stage or in an unscaled container on the stage, and it breaks when in a transformed container. This attempts to address this by getting the coordinates in the local space of the viewport's parent instead of global coordinates.
=> Use viewport parent's local coordinate system rather than global
